# Generated by Django 3.0.9 on 2020-08-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(blank=True, max_length=30, null=True)),
                ('icono', models.FileField(blank=True, null=True, upload_to='media')),
                ('wallpaper_seccion', models.FileField(blank=True, null=True, upload_to='media')),
            ],
            options={
                'verbose_name_plural': '1. Clientes ',
            },
        ),
    ]
