# Generated by Django 3.0.9 on 2020-11-06 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '4. Articulo ',
            },
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevo', models.BooleanField(default=False)),
                ('tema', models.CharField(blank=True, max_length=30, null=True)),
                ('imagen', models.FileField(blank=True, help_text='100x100', null=True, upload_to='media')),
                ('portada', models.FileField(blank=True, help_text='100x100', null=True, upload_to='media')),
                ('icono', models.FileField(blank=True, help_text='100x100', null=True, upload_to='media')),
            ],
            options={
                'verbose_name_plural': '2. Coleccion ',
            },
        ),
        migrations.CreateModel(
            name='Imag_prenda_articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='media')),
            ],
            options={
                'verbose_name_plural': '3. Imag_prenda_articulo ',
            },
        ),
        migrations.CreateModel(
            name='Seccion_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(blank=True, max_length=30, null=True)),
                ('icono', models.FileField(blank=True, null=True, upload_to='media')),
                ('wallpaper_seccion', models.FileField(blank=True, null=True, upload_to='media')),
            ],
            options={
                'verbose_name_plural': '1. Clientes ',
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_visible', models.BooleanField(default=False)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.Articulo')),
                ('coleccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.Coleccion')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.Imag_prenda_articulo')),
            ],
            options={
                'verbose_name_plural': '5. Prenda ',
            },
        ),
        migrations.AddField(
            model_name='coleccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.Seccion_Cliente'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.Seccion_Cliente'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.Imag_prenda_articulo'),
        ),
    ]
