# Generated by Django 3.0.9 on 2020-08-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='media')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.Seccion_Cliente')),
            ],
            options={
                'verbose_name_plural': '3. Prenda ',
            },
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevo', models.BooleanField(default=False)),
                ('tema', models.CharField(blank=True, max_length=30, null=True)),
                ('imagen', models.FileField(blank=True, help_text='100x100', null=True, upload_to='media')),
                ('portada', models.FileField(blank=True, help_text='100x100', null=True, upload_to='media')),
                ('icono', models.FileField(blank=True, help_text='100x100', null=True, upload_to='media')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.Seccion_Cliente')),
            ],
            options={
                'verbose_name_plural': '2. Coleccion ',
            },
        ),
    ]
