# Generated by Django 3.0.9 on 2020-08-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_coleccion_prenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='coleccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.Coleccion'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.Seccion_Cliente'),
        ),
    ]
