# Generated by Django 3.0.9 on 2020-08-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_auto_20200804_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='seccion',
        ),
    ]
