# Generated by Django 3.0.9 on 2020-08-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0005_prenda_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='seccion',
        ),
    ]
