# Generated by Django 3.0.9 on 2020-08-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0006_remove_prenda_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='principal_visible',
            field=models.BooleanField(default=False),
        ),
    ]
