# Generated by Django 3.0.9 on 2020-08-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0007_prenda_principal_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='orden',
        ),
    ]
