# Generated by Django 3.0.9 on 2020-08-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='tipo',
        ),
    ]
