# Generated by Django 3.0.9 on 2020-11-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='video',
            field=models.FileField(blank=True, help_text='imagenes 500*900', null=True, upload_to='slider'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='imagen',
            field=models.ImageField(blank=True, help_text='imagenes 500*900', null=True, upload_to='media'),
        ),
    ]
