# Generated by Django 3.0.9 on 2020-08-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='vortice',
            name='logo_horizontal',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='favicon'),
        ),
    ]
