# Generated by Django 3.0.9 on 2020-11-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_auto_20201121_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='video',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
