# Generated by Django 3.0.9 on 2020-08-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_vortice_logo_horizontal'),
    ]

    operations = [
        migrations.AddField(
            model_name='vortice',
            name='imagen',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='vortice'),
        ),
        migrations.AddField(
            model_name='vortice',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
