# Generated by Django 3.0.9 on 2020-11-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_auto_20201121_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='video',
        ),
    ]
