# Generated by Django 3.0.9 on 2020-08-04 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevo', models.BooleanField(default=False)),
                ('tema', models.CharField(blank=True, max_length=30, null=True)),
                ('imagen', models.FileField(blank=True, help_text='100x100', null=True, upload_to='media')),
                ('portada', models.FileField(blank=True, help_text='100x100', null=True, upload_to='media')),
                ('icono', models.FileField(blank=True, help_text='100x100', null=True, upload_to='media')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.Seccion_Cliente')),
            ],
            options={
                'verbose_name_plural': '2. Coleccion ',
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='media')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.Seccion_Cliente')),
            ],
            options={
                'verbose_name_plural': '3. Prenda ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='media')),
                ('imagen_2', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='media')),
                ('talla', models.CharField(blank=True, choices=[('', ''), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43')], max_length=60, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=999)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Coleccion')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Prenda')),
            ],
            options={
                'verbose_name_plural': '4. Producto ',
            },
        ),
    ]
