# Generated by Django 3.0.9 on 2020-08-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_coleccion_prenda'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='seccion',
        ),
        migrations.AlterField(
            model_name='product',
            name='coleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.Coleccion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.Prenda'),
        ),
        migrations.DeleteModel(
            name='Coleccion',
        ),
        migrations.DeleteModel(
            name='Prenda',
        ),
    ]
