# Generated by Django 3.0.9 on 2020-08-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_auto_20200804_1402'),
        ('products', '0006_auto_20200804_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cliente',
        ),
        migrations.AddField(
            model_name='product',
            name='presnda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.Prenda'),
        ),
    ]
