# Generated by Django 3.0.9 on 2020-08-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200804_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='presnda',
        ),
    ]
