# Generated by Django 3.0.9 on 2020-08-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_auto_20200804_1402'),
        ('products', '0008_remove_product_presnda'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.Prenda'),
        ),
    ]
