# Generated by Django 3.0.9 on 2020-08-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_articulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='articulo',
            new_name='prenda',
        ),
    ]
