# Generated by Django 3.0.9 on 2020-08-04 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0005_prenda_seccion'),
        ('products', '0010_auto_20200804_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.Seccion_Cliente'),
        ),
    ]
