# Generated by Django 3.0.9 on 2020-08-04 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0005_prenda_seccion'),
        ('products', '0011_product_secciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coleccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.Coleccion'),
        ),
    ]
