# Generated by Django 3.0.9 on 2020-08-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_coleccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='coleccion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='secciones',
        ),
    ]
