# Generated by Django 3.0.9 on 2020-08-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200806_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '1. Producto '},
        ),
        migrations.AddField(
            model_name='product',
            name='imagen_3',
            field=models.ImageField(blank=True, help_text='100x100', null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagen_4',
            field=models.ImageField(blank=True, help_text='100x100', null=True, upload_to='media'),
        ),
    ]
